detect_imgsz: 416
detect_ip: 0.0.0.0
detect_model: best_416.pt
detect_port: 9999
image_size: 
- 448
- 800
- 3
life: 10
names: 
  0: pedestrian
  1: compact
  2: general
  3: motorcycle
  4: suv
  5: bus
  6: truck
number_of_cameras: 4
postprocess_path: field
retry_time: 5
