check_frame: 5
detect_imgsz: 416
detect_ip: 0.0.0.0
detect_port: 9999
dist_thr: 5
image_size: [448, 800, 3]
life: 10
names: {0: 'pedestrian', 1: 'compact', 2: 'general', 3: 'motorcycle', 4: 'suv', 5: 'bus', 6: 'truck'}
number_of_cameras: 4
postprocess_path: field
retry_time: 5
rtsp_ip: localhost
rtsp_port: 9999
rtsp_url: video_test
save: False
save_path: None
show: True
stop_life: 60
reverse_life: 5
