from .dialog import Dialog
from .tab_init import TabInit
from .tab_detector import TabDetector
from .tab_event import TabEvent
from .tab_rtsp import TabRtsp
from .tab_simulator import TabSimulator
from .tab_calibration import TabCalibration
from .tab_stitch import TabStit
from .camera.camera import Camera